import { useState, useMemo } from 'react';
import {
  PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Legend
} from 'recharts';
import {
  Info, CheckCircle2, AlertTriangle, RefreshCw, ChevronDown, ChevronUp,
  TrendingUp, Droplets, Shield, Zap
} from 'lucide-react';
import { useFarm } from '../../context/FarmContext';
import {
  PageHeader, DemoBadge, RiskBadge, ConfidenceScore, ScoreBar, InfoNote, SectionLabel
} from '../../components/shared';
import { formatCurrency, formatFullCurrency, cn } from '../../lib/utils';
import { DEMO_PORTFOLIO, DEMO_RECOMMENDATIONS } from '../../data/recommendations';
import { buildPortfolioComparison } from '../../lib/portfolioOptimizer';

export default function PortfolioPage() {
  const { portfolio } = useFarm();
  const p = portfolio ?? DEMO_PORTFOLIO;
  const recs = DEMO_RECOMMENDATIONS;

  // Manual allocation state — clone AI allocations
  const [allocations, setAllocations] = useState(p.allocations.map(a => ({ ...a })));
  const [isManual, setIsManual] = useState(false);
  const [showExplanation, setShowExplanation] = useState(false);
  const [showBreakdown, setShowBreakdown] = useState<string | null>(null);

  const totalLand = p.totalLand;
  const totalAllocated = allocations.reduce((s, a) => s + a.acres, 0);
  const remaining = Math.round((totalLand - totalAllocated) * 10) / 10;
  const isBalanced = Math.abs(remaining) < 0.01;

  const manualProfit = allocations.reduce((s, a) => s + (a.profitPerAcre ?? a.expectedProfit / (a.acres || 1)) * a.acres, 0);

  const updateAcres = (cropId: string, delta: number) => {
    setAllocations(prev =>
      prev.map(a => a.cropId === cropId ? { ...a, acres: Math.max(0, Math.round((a.acres + delta) * 2) / 2) } : a)
    );
    setIsManual(true);
  };

  const resetToAI = () => {
    setAllocations(p.allocations.map(a => ({ ...a })));
    setIsManual(false);
  };

  const pieData = allocations.map(a => ({ name: a.cropName, value: a.acres, color: a.color }));

  // Comparison: AI Portfolio vs Single Crop
  const comparison = useMemo(() => buildPortfolioComparison(recs, p, totalLand), [p, recs, totalLand]);

  const extP = p as typeof p & { optimizationScore?: number; explanations?: string[]; warnings?: string[]; portfolioRiskScore?: number };

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Farm Portfolio Optimizer"
        subtitle="Optimized multi-crop land allocation balancing profit, water fit, risk and diversification"
        badge={<DemoBadge />}
        actions={
          <div className="flex gap-2">
            {isManual && (
              <button onClick={resetToAI} className="btn-secondary text-sm flex items-center gap-1.5">
                <RefreshCw className="w-3.5 h-3.5" /> Reset to AI
              </button>
            )}
          </div>
        }
      />
      <InfoNote variant="warning">
        AI Portfolio Optimizer — MVP Simulation. Land allocation is generated by a deterministic scoring algorithm, not a trained ML model. Expected profit values are illustrative estimates — not guaranteed outcomes.
      </InfoNote>

      {/* Plan mode indicator */}
      {isManual && (
        <div className="flex items-center gap-3 p-3 bg-amber-50 border border-amber-200 rounded-xl">
          <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
          <span className="text-sm text-amber-700 font-medium">Manual Plan — showing your custom allocation. AI recommendation differs.</span>
          <button onClick={resetToAI} className="ml-auto text-xs font-bold text-[#2D6A4F] hover:underline">Reset to AI</button>
        </div>
      )}

      {/* Portfolio Summary KPIs */}
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-5 gap-3">
        <div className="card-sm text-center">
          <div className="text-2xl font-bold text-[#2D6A4F]">{formatCurrency(isManual ? manualProfit : p.expectedTotalProfit)}</div>
          <div className="text-xs text-[#6B7280] mt-0.5">Est. Portfolio Profit</div>
          <div className="text-[10px] text-amber-600">(MVP simulation)</div>
        </div>
        <div className="card-sm text-center">
          <div className="flex items-center justify-center gap-1">
            <RiskBadge risk={p.portfolioRisk} />
          </div>
          <div className="text-xs text-[#6B7280] mt-2">Portfolio Risk</div>
          {extP.portfolioRiskScore !== undefined && (
            <div className="text-[10px] text-[#6B7280]">Score: {extP.portfolioRiskScore}/100</div>
          )}
        </div>
        <div className="card-sm text-center">
          <div className="text-2xl font-bold text-blue-600">{p.waterStressScore}</div>
          <div className="text-xs text-[#6B7280] mt-0.5">Water Stress</div>
          <div className="text-[10px] text-[#6B7280]">0–100 (lower = better)</div>
        </div>
        <div className="card-sm text-center">
          <div className="text-2xl font-bold text-purple-600">{p.diversificationScore}</div>
          <div className="text-xs text-[#6B7280] mt-0.5">Diversification</div>
          <div className="text-[10px] text-[#6B7280]">Shannon entropy metric</div>
        </div>
        {extP.optimizationScore !== undefined && (
          <div className="card-sm text-center">
            <div className="text-2xl font-bold text-amber-600">{extP.optimizationScore}</div>
            <div className="text-xs text-[#6B7280] mt-0.5">Optimization Score</div>
            <ConfidenceScore score={p.confidenceScore} showLabel={false} size="sm" />
          </div>
        )}
      </div>

      {/* Main Portfolio View */}
      <div className="grid md:grid-cols-2 gap-4">
        {/* Donut Chart */}
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <SectionLabel>Land Allocation</SectionLabel>
            <span className="text-xs font-medium text-[#6B7280]">{isManual ? '⚙ Manual Plan' : '🤖 AI Optimized'}</span>
          </div>
          <ResponsiveContainer width="100%" height={230}>
            <PieChart>
              <Pie
                data={pieData}
                cx="50%"
                cy="50%"
                outerRadius={95}
                innerRadius={55}
                dataKey="value"
                paddingAngle={3}
                label={({ name, value }) => `${name}: ${value}ac`}
                labelLine={false}
              >
                {pieData.map((entry, i) => (
                  <Cell key={i} fill={entry.color} />
                ))}
              </Pie>
              <Tooltip formatter={(v) => [`${v} acres`, '']} contentStyle={{ borderRadius: 8, fontSize: 12 }} />
              <Legend wrapperStyle={{ fontSize: 11 }} />
            </PieChart>
          </ResponsiveContainer>
          {/* Allocation bars */}
          <div className="space-y-2 mt-3">
            {allocations.map((a) => (
              <div key={a.cropId} className="flex items-center gap-2">
                <div className="w-2.5 h-2.5 rounded-full shrink-0" style={{ background: a.color }} />
                <span className="text-xs font-medium text-[#1A1A2E] w-24 shrink-0">{a.cropName}</span>
                <ScoreBar value={a.acres} max={totalLand} color={a.color} height={6} />
                <span className="text-xs font-bold text-[#2D6A4F] w-8 shrink-0">{Math.round((a.acres / totalLand) * 100)}%</span>
              </div>
            ))}
          </div>
        </div>

        {/* Adjust Allocation Controls */}
        <div className="card">
          <div className="flex items-center justify-between mb-1">
            <SectionLabel>Adjust Allocation</SectionLabel>
            <span className={cn('text-xs font-bold', isBalanced ? 'text-emerald-600' : 'text-red-500')}>
              {isBalanced ? `✓ ${totalLand} acres allocated` : remaining > 0 ? `${remaining}ac remaining` : `${Math.abs(remaining)}ac excess`}
            </span>
          </div>
          <div className="space-y-4">
            {allocations.map((a) => {
              const profitPerAcre = a.profitPerAcre ?? (a.expectedProfit / (a.acres || 1));
              const displayProfit = formatCurrency(profitPerAcre * a.acres);
              return (
                <div key={a.cropId}>
                  <div className="flex items-center justify-between mb-1.5">
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 rounded-sm shrink-0" style={{ background: a.color }} />
                      <span className="text-sm font-semibold text-[#1A1A2E]">{a.cropName}</span>
                      {a.riskLevel && <RiskBadge risk={a.riskLevel} className="text-[9px] py-0 px-1.5" />}
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => updateAcres(a.cropId, -0.5)}
                        className="w-6 h-6 rounded-full bg-gray-100 hover:bg-gray-200 text-sm font-bold flex items-center justify-center"
                      >−</button>
                      <span className="text-sm font-bold w-16 text-center">{a.acres} acres</span>
                      <button
                        onClick={() => updateAcres(a.cropId, 0.5)}
                        className="w-6 h-6 rounded-full bg-[#E8F5EE] hover:bg-[#D1FAE5] text-[#2D6A4F] text-sm font-bold flex items-center justify-center"
                      >+</button>
                    </div>
                  </div>
                  <ScoreBar value={a.acres} max={totalLand} color={a.color} height={7} />
                  <div className="flex justify-between text-xs text-[#6B7280] mt-0.5">
                    <span>{Math.round((a.acres / (totalAllocated || 1)) * 100)}%</span>
                    <span>{displayProfit} est. profit</span>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="pt-3 mt-3 border-t border-[#E5E0D8] flex justify-between items-center text-sm font-bold">
            <span>Total</span>
            <span className={isBalanced ? 'text-emerald-600' : 'text-red-500'}>
              {totalAllocated} / {totalLand} acres
            </span>
          </div>
          {!isBalanced && (
            <InfoNote variant="warning">
              {remaining > 0
                ? `${remaining} acre(s) of land are unallocated.`
                : `Allocation exceeds available land by ${Math.abs(remaining)} acre(s).`}
            </InfoNote>
          )}
        </div>
      </div>

      {/* Per-crop Detail Cards */}
      <div className="grid md:grid-cols-2 gap-4">
        {p.allocations.map((a) => {
          const rec = recs.find(r => r.cropId === a.cropId);
          const expanded = showBreakdown === a.cropId;
          return (
            <div key={a.cropId} className={cn('card border-l-4 transition-all', `border-l-[${a.color}]`)}>
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-2">
                  <div className="w-3.5 h-3.5 rounded-full shrink-0" style={{ background: a.color }} />
                  <div>
                    <div className="font-bold text-[#1A1A2E]">{a.cropName}</div>
                    <div className="text-xs text-[#6B7280]">{a.acres} acres · {a.percentage}%</div>
                  </div>
                </div>
                <div className="text-right">
                  <div className="font-bold text-[#2D6A4F]">{formatCurrency(a.expectedProfit)}</div>
                  <div className="text-[10px] text-[#6B7280]">est. profit</div>
                </div>
              </div>

              <div className="grid grid-cols-4 gap-1.5 mb-3">
                {[
                  { label: 'Soil', value: rec?.soilCompatibility, icon: '🌱', color: '#D4A017' },
                  { label: 'Water', value: rec?.waterFitScore ?? (100 - (rec?.waterStressPct ?? 0)), icon: '💧', color: '#2D6A4F' },
                  { label: 'Market', value: rec?.marketCompatibility, icon: '📈', color: '#8B5CF6' },
                  { label: 'Risk Fit', value: rec ? 100 - rec.riskScore : 0, icon: '🛡', color: '#059669' },
                ].map(({ label, value, icon, color }) => (
                  <div key={label} className="bg-[#F8F5F0] rounded-lg p-1.5 text-center">
                    <div className="text-base">{icon}</div>
                    <div className="text-[10px] text-[#6B7280]">{label}</div>
                    <div className="text-xs font-bold" style={{ color }}>{value ?? '—'}</div>
                  </div>
                ))}
              </div>

              <button
                onClick={() => setShowBreakdown(expanded ? null : a.cropId)}
                className="text-xs text-[#2D6A4F] font-semibold flex items-center gap-1 hover:underline w-full"
              >
                {expanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                {expanded ? 'Hide Details' : 'Why this allocation?'}
              </button>

              {expanded && rec && (
                <div className="mt-3 pt-3 border-t border-[#E5E0D8] space-y-1.5">
                  {rec.reasons.slice(0, 3).map((r, i) => (
                    <div key={i} className="flex items-start gap-1.5 text-xs text-[#4B5563]">
                      <CheckCircle2 className="w-3 h-3 shrink-0 mt-0.5 text-emerald-500" /> {r}
                    </div>
                  ))}
                  {rec.warnings.slice(0, 2).map((w, i) => (
                    <div key={i} className="flex items-start gap-1.5 text-xs text-amber-600">
                      <AlertTriangle className="w-3 h-3 shrink-0 mt-0.5" /> {w}
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Portfolio vs Single Crop Comparison */}
      <div className="card">
        <div className="flex items-center justify-between mb-4">
          <SectionLabel>AI Portfolio vs. Single-Crop Strategy</SectionLabel>
          <DemoBadge />
        </div>
        <div className="grid md:grid-cols-2 gap-6">
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={[
              { strategy: `Single Crop\n(${comparison.singleCrop.cropName})`, profit: comparison.singleCrop.expectedProfit, color: '#E76F51' },
              { strategy: 'AI Portfolio', profit: p.expectedTotalProfit, color: '#2D6A4F' },
            ]}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#F0EDE8" />
              <XAxis dataKey="strategy" tick={{ fontSize: 10, fill: '#6B7280' }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 10, fill: '#6B7280' }} axisLine={false} tickLine={false} tickFormatter={v => `₹${(v / 100000).toFixed(1)}L`} />
              <Tooltip formatter={(v) => [formatFullCurrency(Number(v)), 'Est. Profit']} contentStyle={{ borderRadius: 8, fontSize: 12 }} />
              <Bar dataKey="profit" radius={[6, 6, 0, 0]}>
                <Cell fill="#E76F51" />
                <Cell fill="#2D6A4F" />
              </Bar>
            </BarChart>
          </ResponsiveContainer>

          <div className="space-y-2">
            {[
              {
                label: 'Est. Profit', icon: TrendingUp,
                single: formatCurrency(comparison.singleCrop.expectedProfit),
                portfolio: formatCurrency(p.expectedTotalProfit),
                betterPortfolio: p.expectedTotalProfit >= comparison.singleCrop.expectedProfit,
              },
              {
                label: 'Risk', icon: Shield,
                single: `${comparison.singleCrop.riskScore}/100 (concentrated)`,
                portfolio: `${extP.portfolioRiskScore ?? p.waterStressScore}/100 (diversified)`,
                betterPortfolio: (extP.portfolioRiskScore ?? 50) < comparison.singleCrop.riskScore,
              },
              {
                label: 'Diversification', icon: Zap,
                single: 'None (1 crop)',
                portfolio: `${p.diversificationScore}/100`,
                betterPortfolio: true,
              },
              {
                label: 'Water Stress', icon: Droplets,
                single: `${comparison.singleCrop.waterStress}%`,
                portfolio: `${p.waterStressScore}%`,
                betterPortfolio: p.waterStressScore <= comparison.singleCrop.waterStress,
              },
            ].map(({ label, icon: Icon, single, portfolio, betterPortfolio }) => (
              <div key={label} className="grid grid-cols-[100px_1fr_1fr] gap-2 text-xs items-center">
                <div className="flex items-center gap-1 font-medium text-[#6B7280]">
                  <Icon className="w-3 h-3" /> {label}
                </div>
                <div className={cn('text-center px-2 py-1 rounded-lg', !betterPortfolio ? 'bg-emerald-100 text-emerald-700 font-bold' : 'bg-[#F8F5F0] text-[#6B7280]')}>{single}</div>
                <div className={cn('text-center px-2 py-1 rounded-lg', betterPortfolio ? 'bg-emerald-100 text-emerald-700 font-bold' : 'bg-[#F8F5F0] text-[#6B7280]')}>{portfolio}</div>
              </div>
            ))}
            <div className="text-[10px] text-[#6B7280] pt-2 border-t border-[#E5E0D8]">
              ⚠ Portfolio profit may not always exceed single-crop. Portfolio benefit is risk reduction and diversification — not guaranteed higher income. All values are MVP simulation estimates.
            </div>
          </div>
        </div>
      </div>

      {/* Why This Allocation */}
      <div className="card border-l-4 border-l-[#2D6A4F]">
        <button className="w-full flex items-center justify-between" onClick={() => setShowExplanation(!showExplanation)}>
          <div className="flex items-center gap-2">
            <Info className="w-5 h-5 text-[#2D6A4F]" />
            <span className="font-semibold text-[#1A1A2E]">Why This Allocation?</span>
            <span className="text-xs text-[#6B7280]">AI Portfolio Optimizer Explanation</span>
          </div>
          {showExplanation ? <ChevronUp className="w-4 h-4 text-[#2D6A4F]" /> : <ChevronDown className="w-4 h-4 text-[#2D6A4F]" />}
        </button>
        {showExplanation && (
          <div className="mt-4 space-y-3">
            {(extP.explanations ?? [p.explanation]).map((exp, i) => (
              <div key={i} className="flex items-start gap-2 text-sm text-[#4B5563]">
                <CheckCircle2 className="w-4 h-4 shrink-0 mt-0.5 text-emerald-500" /> {exp}
              </div>
            ))}
            {extP.warnings && extP.warnings.length > 0 && (
              <div className="mt-3 pt-3 border-t border-[#E5E0D8]">
                <div className="text-xs font-semibold text-amber-600 mb-2">⚠ Portfolio Warnings</div>
                {extP.warnings.map((w, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs text-amber-700 mb-1.5">
                    <AlertTriangle className="w-3 h-3 shrink-0 mt-0.5" /> {w}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
