// ============================================================
// MittiMitra AI — Recommendations & Portfolio (Engine-Driven)
// ============================================================
//
// IMPORTANT: This file contains NO hardcoded crop scores or
// portfolio allocations. Everything is generated by:
//
//   1. runAIDecisionEngine()    → DEMO_RECOMMENDATIONS
//   2. optimizeCropPortfolio()  → DEMO_PORTFOLIO
//
// To change recommendations, update mock data in:
//   src/data/soil.ts, weather.ts, market.ts, farms.ts, crops.ts
//
// Label: "AI Decision Engine + Portfolio Optimizer — MVP Simulation"
// ============================================================

import type { RecommendationRecord } from '../types';
import { runAIDecisionEngine } from '../lib/engine';
import { optimizeCropPortfolio } from '../lib/portfolioOptimizer';
import { DEMO_SOIL } from './soil';
import { DEMO_WEATHER, DEMO_WATER } from './weather';
import { DEMO_MARKET } from './market';
import { DEMO_CROP_HISTORY, DEMO_FARM } from './farms';
import { CROPS } from './crops';

// ── 1. AI Decision Engine output ─────────────────────────────
// Single source of truth for all crop recommendations.

export const DEMO_RECOMMENDATIONS = runAIDecisionEngine(
  DEMO_SOIL,
  DEMO_WEATHER,
  DEMO_WATER,
  DEMO_MARKET,
  DEMO_CROP_HISTORY,
  CROPS
);

// ── 2. Portfolio Optimizer output ─────────────────────────────
// Single source of truth for land allocation.
// Consumes DEMO_RECOMMENDATIONS — does NOT recalculate crop scores.

export const DEMO_PORTFOLIO = optimizeCropPortfolio(
  DEMO_FARM.totalLand,
  DEMO_RECOMMENDATIONS,
  DEMO_WATER
);

// ── 3. Recommendation History (static demo records) ──────────

export const RECOMMENDATION_HISTORY: RecommendationRecord[] = [
  {
    id: 'rec-001',
    farmId: 'demo-farm-1',
    farmName: 'Demo Farm',
    date: '2024-10-15',
    portfolio: DEMO_PORTFOLIO.allocations,
    expectedProfit: DEMO_PORTFOLIO.expectedTotalProfit,
    riskLevel: DEMO_PORTFOLIO.portfolioRisk,
    confidenceScore: DEMO_PORTFOLIO.confidenceScore,
    status: 'in_progress',
  },
  {
    id: 'rec-002',
    farmId: 'demo-farm-1',
    farmName: 'Demo Farm',
    date: '2024-04-10',
    portfolio: [
      { cropId: 'maize', cropName: 'Maize', cropNameHi: 'मक्का', acres: 6, percentage: 60, expectedProfit: 100200, waterStress: 24, riskScore: 45, color: '#52B788' },
      { cropId: 'vegetable', cropName: 'Mixed Vegetables', cropNameHi: 'मिश्रित सब्जियां', acres: 4, percentage: 40, expectedProfit: 176000, waterStress: 5, riskScore: 52, color: '#D4A017' },
    ],
    expectedProfit: 276200,
    riskLevel: 'medium',
    confidenceScore: 76,
    status: 'completed',
  },
];
